spring:
   corsConfigurations:
          '[/**]':
            allowedOrigins: "**"
            allowedHeaders: "********************************"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE